// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"Plugin used to set basic parameters.","parameters":{"cacheLimit":"20","screenWidth":"1280","screenHeight":"720","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"WindowIdentifier","status":false,"description":"Shows the name of the windows while holding CTRL.","parameters":{"Font Size":"28","Font Color":"0"}},
{"name":"NoAntiAliasing","status":true,"description":"","parameters":{}},
{"name":"CP_Large_Sprite_Fix","status":true,"description":"Fixes an issue with large sprites appearing under ☆ passability tiles.","parameters":{"Terrain ID":"7","Large Followers":"No","Large Vehicles":"Yes"}},
{"name":"-----------------","status":false,"description":"","parameters":{}},
{"name":"DQE_Misc","status":true,"description":"Misc changes for Dragon Quest Engine - V0.1","parameters":{}},
{"name":"DQE_Window_Message","status":true,"description":"Message window for Dragon Quest Engine - V0.1","parameters":{}}
];
